################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
CustomEdh/AD5592R \
CustomEdh/ADF4372 \
CustomEdh/CLI \
CustomEdh/ETH \
CustomEdh/ExtFlash \
CustomEdh/FRAM \
CustomEdh/GSL1680F \
CustomEdh/Image_Test \
CustomEdh/Init \
CustomEdh/TaskCLI \
CustomEdh/TaskForTest \
CustomEdh/TaskGFX \
CustomEdh/TaskSint \
CustomEdh/Task_Bias_Pwrctrl \
CustomEdh/Tasklvgl \
CustomEdh/Utility \
Drivers/BSP/Components/lan8742 \
Drivers/STM32H7xx_HAL_Driver/Src \
LWIP/App \
LWIP/Target \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/Third_Party/LwIP/src/api \
Middlewares/Third_Party/LwIP/src/apps/mqtt \
Middlewares/Third_Party/LwIP/src/core \
Middlewares/Third_Party/LwIP/src/core/ipv4 \
Middlewares/Third_Party/LwIP/src/core/ipv6 \
Middlewares/Third_Party/LwIP/src/netif \
Middlewares/Third_Party/LwIP/src/netif/ppp \
Middlewares/Third_Party/LwIP/system/OS \
display_lvgl \
lvgl/examples/anim \
lvgl/examples/assets \
lvgl/examples/assets/emoji \
lvgl/examples/event \
lvgl/examples/get_started \
lvgl/examples/layouts/flex \
lvgl/examples/layouts/grid \
lvgl/examples/libs/barcode \
lvgl/examples/libs/bmp \
lvgl/examples/libs/ffmpeg \
lvgl/examples/libs/freetype \
lvgl/examples/libs/gif \
lvgl/examples/libs/libjpeg_turbo \
lvgl/examples/libs/libpng \
lvgl/examples/libs/lodepng \
lvgl/examples/libs/qrcode \
lvgl/examples/libs/rlottie \
lvgl/examples/libs/tiny_ttf \
lvgl/examples/libs/tjpgd \
lvgl/examples/others/file_explorer \
lvgl/examples/others/fragment \
lvgl/examples/others/gridnav \
lvgl/examples/others/ime \
lvgl/examples/others/imgfont \
lvgl/examples/others/monkey \
lvgl/examples/others/observer \
lvgl/examples/others/snapshot \
lvgl/examples/porting \
lvgl/examples/scroll \
lvgl/examples/styles \
lvgl/examples/widgets/animimg \
lvgl/examples/widgets/arc \
lvgl/examples/widgets/bar \
lvgl/examples/widgets/button \
lvgl/examples/widgets/buttonmatrix \
lvgl/examples/widgets/calendar \
lvgl/examples/widgets/canvas \
lvgl/examples/widgets/chart \
lvgl/examples/widgets/checkbox \
lvgl/examples/widgets/dropdown \
lvgl/examples/widgets/image \
lvgl/examples/widgets/imagebutton \
lvgl/examples/widgets/keyboard \
lvgl/examples/widgets/label \
lvgl/examples/widgets/led \
lvgl/examples/widgets/line \
lvgl/examples/widgets/list \
lvgl/examples/widgets/menu \
lvgl/examples/widgets/msgbox \
lvgl/examples/widgets/obj \
lvgl/examples/widgets/roller \
lvgl/examples/widgets/scale \
lvgl/examples/widgets/slider \
lvgl/examples/widgets/span \
lvgl/examples/widgets/spinbox \
lvgl/examples/widgets/spinner \
lvgl/examples/widgets/switch \
lvgl/examples/widgets/table \
lvgl/examples/widgets/tabview \
lvgl/examples/widgets/textarea \
lvgl/examples/widgets/tileview \
lvgl/examples/widgets/win \
lvgl/src/core \
lvgl/src/dev/display/drm \
lvgl/src/dev/display/fb \
lvgl/src/dev/display/tft_espi \
lvgl/src/dev/evdev \
lvgl/src/dev/nuttx \
lvgl/src/dev/sdl \
lvgl/src/dev/x11 \
lvgl/src/display \
lvgl/src/draw \
lvgl/src/draw/nxp/pxp \
lvgl/src/draw/nxp/vglite \
lvgl/src/draw/renesas/dave2d \
lvgl/src/draw/sdl \
lvgl/src/draw/sw/blend \
lvgl/src/draw/sw/blend/neon \
lvgl/src/draw/sw \
lvgl/src/draw/vg_lite \
lvgl/src/font \
lvgl/src/indev \
lvgl/src/layouts/flex \
lvgl/src/layouts/grid \
lvgl/src/layouts \
lvgl/src/libs/barcode \
lvgl/src/libs/bin_decoder \
lvgl/src/libs/bmp \
lvgl/src/libs/ffmpeg \
lvgl/src/libs/freetype \
lvgl/src/libs/fsdrv \
lvgl/src/libs/gif \
lvgl/src/libs/libjpeg_turbo \
lvgl/src/libs/libpng \
lvgl/src/libs/lodepng \
lvgl/src/libs/lz4 \
lvgl/src/libs/qrcode \
lvgl/src/libs/rle \
lvgl/src/libs/rlottie \
lvgl/src/libs/thorvg \
lvgl/src/libs/tiny_ttf \
lvgl/src/libs/tjpgd \
lvgl/src \
lvgl/src/misc \
lvgl/src/osal \
lvgl/src/others/file_explorer \
lvgl/src/others/fragment \
lvgl/src/others/gridnav \
lvgl/src/others/ime \
lvgl/src/others/imgfont \
lvgl/src/others/monkey \
lvgl/src/others/observer \
lvgl/src/others/snapshot \
lvgl/src/others/sysmon \
lvgl/src/stdlib/builtin \
lvgl/src/stdlib/clib \
lvgl/src/stdlib \
lvgl/src/stdlib/micropython \
lvgl/src/stdlib/rtthread \
lvgl/src/themes/default \
lvgl/src/themes \
lvgl/src/themes/mono \
lvgl/src/themes/simple \
lvgl/src/tick \
lvgl/src/widgets/animimage \
lvgl/src/widgets/arc \
lvgl/src/widgets/bar \
lvgl/src/widgets/button \
lvgl/src/widgets/buttonmatrix \
lvgl/src/widgets/calendar \
lvgl/src/widgets/canvas \
lvgl/src/widgets/chart \
lvgl/src/widgets/checkbox \
lvgl/src/widgets/dropdown \
lvgl/src/widgets/image \
lvgl/src/widgets/imagebutton \
lvgl/src/widgets/keyboard \
lvgl/src/widgets/label \
lvgl/src/widgets/led \
lvgl/src/widgets/line \
lvgl/src/widgets/list \
lvgl/src/widgets/menu \
lvgl/src/widgets/msgbox \
lvgl/src/widgets/objx_templ \
lvgl/src/widgets/roller \
lvgl/src/widgets/scale \
lvgl/src/widgets/slider \
lvgl/src/widgets/span \
lvgl/src/widgets/spinbox \
lvgl/src/widgets/spinner \
lvgl/src/widgets/switch \
lvgl/src/widgets/table \
lvgl/src/widgets/tabview \
lvgl/src/widgets/textarea \
lvgl/src/widgets/tileview \
lvgl/src/widgets/win \

